version: "3"
services:
  vue-ui:
    build:
      context: ./vue-spa
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./vue-spa:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules
  keystonejs:
    image: ntutselab/keystonejs
    ports:
      - "3000:3000"
    # entrypoint: /app
    links:
      - mongodb
    # volumes:
    #   - ./keystonejs/:/app
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
